[firewall]
fw_node ansible_host= 192.168.x.x frontend_ip=10.0.1.1 dmz_ip= 10.0.2.1 backend_ip=10.0.3.1

[web]
web_node ansible_host=192.168.x.x internal_ip=10.0.2.2 

[db]
db_node ansible_host= 192.168.x.x internal_ip=10.0.3.2

[client]
localhost ansible_connection=local