[firewall]
fw_node ansible_host=10.0.1.1 ansible_connection=local frontend_ip=10.0.1.1 dmz_ip=10.0.5.1 backend_ip=10.0.3.1

[client]
client_node ansible_host=10.0.1.2

[webserver]
web_node ansible_host=10.0.5.2

[database]
db_node ansible_host=10.0.3.2 

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/vagrant/.vagrant/machines/{{ 'firewall' if inventory_hostname == 'fw_node' else 'webserver' if inventory_hostname == 'web_node' else 'database' if inventory_hostname == 'db_node' else 'client' }}/virtualbox/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'